### ISSUE TITLE
Doesnt work with Adapt 4.0

### ISSUE THREAD

**Issue by robmausser** [adaptlearning/adapt-contrib-pointGmcq#19]
Any chance this could be updated to work with Adapt 4.0

**Comment by moloko** [comment]
could you be more specific about how exactly it doesn't work?

**Comment by robertmausser** [comment]
The entire adapt course fails to load with the error:

Uncaught TypeError: Mcq.extend is not a function
    at adapt.min.js:12015
    at Object.execCb (require.min.js:29)
    at da.check (require.min.js:18)
    at da.enable (require.min.js:23)
    at Object.enable (require.min.js:27)
    at da.<anonymous> (require.min.js:22)
    at require.min.js:7
    at y (require.min.js:6)
    at da.enable (require.min.js:21)
    at Object.enable (require.min.js:27)

I believe the MCQ component which this relies on has been rewritten in a way its not compatible anymore

**Comment by moloko** [comment]
oh yes I see what you mean now! In fact there's already a ticket about this - #17 

I'll see if anyone has time to take a look

**Comment by robertmausser** [comment]
thanks!!

Rob Mausser
Intermediate Interactive Developer
m 416 931 6223 <4169316223>  o 416 598 1200 x115 <4165981200,115>

*REDWOOD PERFORMANCE GROUP*

redwoodperforms.com

Redwood Performance Group plans and innovates with you to address your
biggest performance and engagement challenges.

IMPORTANT NOTICE: This message is intended only for the use of the
individual or entity to which it is addressed. If the reader of this
message is not the intended recipient, or the employee or agent responsible
for delivering the message to the intended recipient, you are notified that
any dissemination, distribution or copying of this communication is
strictly prohibited. If you have received this communication in error,
please notify Redwood Performance Group immediately by email at
info@redwoodperforms.com. Thank you.
